# Generated by Django 5.2.7 on 2025-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
