# Generated by Django 5.2.7 on 2025-10-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_invoice_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='invoice_pdf',
        ),
    ]
