# Generated by Django 5.2.7 on 2025-11-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bill_payment_status'),
        ('products', '0025_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
