# Generated by Django 5.2.7 on 2025-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
