# Generated by Django 5.2.7 on 2025-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('admin', 'admin')], default='cashier', max_length=20),
        ),
    ]
