# Generated by Django 5.2.7 on 2025-10-31 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 10, 55, 38, 748598, tzinfo=datetime.timezone.utc)),
        ),
    ]
