# Generated by Django 5.2.7 on 2025-10-31 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 11, 59, 3, 197975, tzinfo=datetime.timezone.utc)),
        ),
    ]
