# Generated by Django 5.2.7 on 2025-10-31 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 16, 31, 45, 286527, tzinfo=datetime.timezone.utc)),
        ),
    ]
