# Generated by Django 5.2.7 on 2025-11-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 7, 38, 24, 618938, tzinfo=datetime.timezone.utc)),
        ),
    ]
