# Generated by Django 5.2.7 on 2025-11-02 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 8, 25, 58, 591788, tzinfo=datetime.timezone.utc)),
        ),
    ]
