# Generated by Django 5.2.7 on 2025-11-02 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_supplier_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 9, 9, 31, 546947, tzinfo=datetime.timezone.utc)),
        ),
    ]
