# Generated by Django 5.2.7 on 2025-11-02 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 9, 14, 49, 892668, tzinfo=datetime.timezone.utc)),
        ),
    ]
