# Generated by Django 5.2.7 on 2025-11-02 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_item_id_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 16, 59, 10, 489364, tzinfo=datetime.timezone.utc)),
        ),
    ]
