# Generated by Django 5.2.7 on 2025-11-02 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 17, 38, 40, 903036, tzinfo=datetime.timezone.utc)),
        ),
    ]
