# Generated by Django 5.2.7 on 2025-11-03 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 19, 6, 20, 10936, tzinfo=datetime.timezone.utc)),
        ),
    ]
