# Generated by Django 5.2.7 on 2025-11-03 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 20, 28, 37, 739020, tzinfo=datetime.timezone.utc)),
        ),
    ]
