# Generated by Django 5.2.7 on 2025-11-06 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_stockentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 15, 36, 14, 918740, tzinfo=datetime.timezone.utc)),
        ),
    ]
